export default{
    state:{
        isLogin:false,
        name:'',
        address:[]
    },
    mutations:{
        dispathLogin(state,userInfo){
            state.isLogin=userInfo.isLogin;
            state.name=userInfo.name;
        },
        dispathAddress(state,address){
            state.address=address;
        },
        addAddress(state,address){
            console.log(state.address)
            state.address.push(address);
        },
        delAddress(state,address){
            state.address.splice(state.address.indexOf(address),1);
        }
    },
    actions:{
        /*辣鸡vuex。。。。*/
        dispathLogin({state,commit},userInfo){
            commit('dispathLogin',userInfo);
        },
        addAddress({state,commit},address){
            commit('addAddress',address);
        },
        delAddress({state,commit},address){
            commit('delAddress',address);
        },
        dispathAddress({state,commit},address){
            commit('dispathAddress',address);
        },
    }
}